@BookingHotel_HostAddress = http://localhost:5063
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMTYyMDg1YS01MzI0LTQ0ZmUtYWFiZi1jM2I0MDI1ZTQ5MmMiLCJlbWFpbCI6ImFiY2Rlc2ZhYXcydzJzQGV4YW1wbGUuY29tIiwianRpIjoiNjhmYzBmMTItNGVjNC00NTMxLThlZGEtOGEzOWE5Yzc3MWYwIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWJjZGVzZmFhdzJ3MnNAZXhhbXBsZS5jb20iLCJleHAiOjE3ODMyMDM0MTYsImlzcyI6IkJvb2tpbmdIb3RlbEFQSSIsImF1ZCI6IkJvb2tpbmdIb3RlbEFQSUNsaWVudCJ9.HuhjtLVhfQgg0e047S6Zh2FcF8D-ESXaGIUU7ddVNag

### 
GET http://localhost:5063/api/Hotels

###
POST {{BookingHotel_HostAddress}}/api/Hotels
Content-Type: application/json

{
  "Name" : "Masoud",
  "Address" : "Gorgan",
  "Rating" : 4.1,
  "CountryId" : 1
}

###
GET http://localhost:5063/api/Hotels/2

###
@id=2
PUT http://localhost:5063/api/Hotels/{{id}}
Content-Type: application/json

{
  "Id" : 2,
    "Name" : "Azin",
    "Address" : "Gorgan",
    "Rating" : 4.2,
  "CountryId" : 1
}

###
DELETE http://localhost:5063/api/Hotels/2

###
POST {{BookingHotel_HostAddress}}/api/Countries
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Name" : "France",
  "ShortName" : "FR"
}
###
GET {{BookingHotel_HostAddress}}/api/Countries
Authorization: Bearer {{Token}}

###
GET {{BookingHotel_HostAddress}}/api/Countries/1


### 1. Register a new user
POST {{BookingHotel_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "abcdesfaaw2w2s@example.com",
  "password": "Password@123!"
}

### login
POST {{BookingHotel_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "abcdesfaaw2w2s@example.com",
  "password": "Password@123!"
}