@BookingHotel_HostAddress = http://localhost:5063

GET {{BookingHotel_HostAddress}}/weatherforecast/
Accept: application/json

### 
GET http://localhost:5063/api/Hotels

###
POST http://localhost:5063/api/Hotels
Content-Type: application/json

{
  "Id" : 3, 
  "Name" : "Masoud",
  "Address" : "Gorgan",
  "Rating" : 4.1
}

###
GET http://localhost:5063/api/Hotels/1

###
@id=3
PUT http://localhost:5063/api/Hotels/{{id}}
Content-Type: application/json

{
    "Name" : "Masoud2",
    "Address" : "Gorgan2",
    "Rating" : 4.1
}

###
DELETE http://localhost:5063/api/Hotels/2

###
POST {{BookingHotel_HostAddress}}/api/Country
Content-Type: application/json
 
{
  "Name" : "Iran",
  "ShortName" : "IR"
}