@BookingHotel_HostAddress = http://localhost:5063

GET {{BookingHotel_HostAddress}}/weatherforecast/
Accept: application/json

### 
GET http://localhost:5063/api/Hotels

###
POST {{BookingHotel_HostAddress}}/api/Hotels
Content-Type: application/json

{
  "Name" : "Masoud",
  "Address" : "Gorgan",
  "Rating" : 4.1,
  "CountryId" : 1
}

###
GET http://localhost:5063/api/Hotels/2

###
@id=2
PUT http://localhost:5063/api/Hotels/{{id}}
Content-Type: application/json

{
  "Id" : 2,
    "Name" : "Azin",
    "Address" : "Gorgan",
    "Rating" : 4.2,
  "CountryId" : 1
}

###
DELETE http://localhost:5063/api/Hotels/2

###
POST {{BookingHotel_HostAddress}}/api/Country
Content-Type: application/json
 
{
  "Name" : "Iran",
  "ShortName" : "IR"
}
###
GET {{BookingHotel_HostAddress}}/api/Country

###
GET {{BookingHotel_HostAddress}}/api/Country/1